spring:
  application:
    name: self-archive

  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} : %msg%n"