spring:
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=UTF-8&serverTimezone=UCT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: TRACE


